version: '3.1'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: mujib.org
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: mujib.org
      LETSENCRYPT_EMAIL: shuhan.mirza@gmail.com
networks:
  default:
    external:
      name: nginx-proxy

volumes:
  data: